package com.wadpam.gaelic.oauth.dao;

import com.wadpam.gaelic.oauth.domain.DConnection;

/**
 * Business Methods interface for entity DConnection.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-09T05:56:26.129+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DConnectionDao extends GeneratedDConnectionDao {

    Iterable<DConnection> queryByProviderIdProviderUserId(String providerId, String providerUserId);
	
}
