package com.wadpam.gaelic.oauth.dao;

/**
 * Implementation of Business Methods related to entity DOAuth2User.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-09T05:56:26.129+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DOAuth2UserDaoBean 
	extends GeneratedDOAuth2UserDaoImpl
		implements DOAuth2UserDao 
{

	// TODO: implement your Business Methods here

}
