package com.wadpam.gaelic.oauth.provider.dao;

/**
 * Implementation of Business Methods related to entity Do2pProfile.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-07-17T09:56:12.209+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class Do2pProfileDaoBean 
	extends GeneratedDo2pProfileDaoImpl
		implements Do2pProfileDao 
{

	// TODO: implement your Business Methods here

}
