package com.wadpam.gaelic.oauth.provider.dao;

/**
 * Implementation of Business Methods related to entity Do2pClient.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-07-18T12:02:44.205+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class Do2pClientDaoBean 
	extends GeneratedDo2pClientDaoImpl
		implements Do2pClientDao 
{

	// TODO: implement your Business Methods here

}
