package com.wadpam.gaelic.oauth.provider.dao;

/**
 * Business Methods interface for entity Do2pProfile.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-07-17T09:56:12.209+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface Do2pProfileDao extends GeneratedDo2pProfileDao {

	// TODO: declare your Business Methods here
	
}
