package com.wadpam.gaelic.oauth.provider.dao;

/**
 * Business Methods interface for entity Do2pToken.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-07-18T12:02:44.205+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface Do2pTokenDao extends GeneratedDo2pTokenDao {

	// TODO: declare your Business Methods here
	
}
