package com.wadpam.gaelic.dao;

import java.util.HashMap;
import java.util.Map;
import net.sf.mardao.core.dao.DaoImpl;
import com.wadpam.gaelic.domain.DDate;

/**
 * Context to define the Dao beans.
 * This file is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-07-11T17:23:15.598+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DaoConfig {

    public static Map<Class, DaoImpl> createDaos() {
        final HashMap<Class, DaoImpl> map = new HashMap<Class, DaoImpl>();

        // first, create and map Dao instances:
        final DDateDaoBean dDateDao =
            new DDateDaoBean();
        map.put(DDate.class, dDateDao);

        // next, wire parents;

        // finally, wire many-to-ones;
	
        return map;
    }
}