package com.wadpam.gaelic.dao;

/**
 * Business Methods interface for entity DDate.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-06T09:20:59.186+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DDateDao extends GeneratedDDateDao {

	// TODO: declare your Business Methods here
	
}
