package com.wadpam.gaelic.dao;

/**
 * Implementation of Business Methods related to entity DDate.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-06T09:20:59.186+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DDateDaoBean 
	extends GeneratedDDateDaoImpl
		implements DDateDao 
{

	// TODO: implement your Business Methods here

}
