package com.wadpam.gaelic.dao;

/**
 * Business Methods interface for entity DAppDomain.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-17T21:28:31.839+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface DAppDomainDao extends GeneratedDAppDomainDao {

	// TODO: declare your Business Methods here
	
}
