#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${package}.dao;

/**
 * Implementation of Business Methods related to entity DSample.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-05-15T16:11:37.205+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DSampleDaoBean 
	extends GeneratedDSampleDaoImpl
		implements DSampleDao 
{

	// TODO: implement your Business Methods here

}
